//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooknowAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingDecores = new HashSet<BookingDecore>();
            this.Jukeboxes = new HashSet<Jukebox>();
            this.Orders = new HashSet<Order>();
            this.Ratings = new HashSet<Rating>();
            this.WaiterAssignments = new HashSet<WaiterAssignment>();
        }
    
        public int BookingId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public Nullable<System.DateTime> BookingDateTime { get; set; }
        public string SpecialRequest { get; set; }
        public string Status { get; set; }
        public Nullable<int> TableId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDecore> BookingDecores { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jukebox> Jukeboxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaiterAssignment> WaiterAssignments { get; set; }
        public virtual Table Table { get; set; }
    }
}
