//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooknowAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCoin
    {
        public int CustomerCoinId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CoinCategoryId { get; set; }
        public Nullable<int> Balance { get; set; }
    
        public virtual CoinCategory CoinCategory { get; set; }
        public virtual User User { get; set; }
    }
}
