//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooknowAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.DishRecipes = new HashSet<DishRecipe>();
            this.StockConsumptions = new HashSet<StockConsumption>();
        }
    
        public int IngredientId { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> QuantityInStock { get; set; }
        public Nullable<int> restaurant_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DishRecipe> DishRecipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockConsumption> StockConsumptions { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
