//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooknowAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jukebox
    {
        public int JukeboxId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> MusicId { get; set; }
        public Nullable<int> CoinCategoryId { get; set; }
        public Nullable<int> CoinsSpent { get; set; }
        public string DedicationNote { get; set; }
        public Nullable<System.DateTime> RequestedAt { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual CoinCategory CoinCategory { get; set; }
        public virtual Music Music { get; set; }
        public virtual User User { get; set; }
    }
}
