//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooknowAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class newRestdbEntities : DbContext
    {
        public newRestdbEntities()
            : base("name=newRestdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<BookingDecore> BookingDecores { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<ChefDishSpeciality> ChefDishSpecialities { get; set; }
        public virtual DbSet<Chef> Chefs { get; set; }
        public virtual DbSet<CoinCategory> CoinCategories { get; set; }
        public virtual DbSet<CustomerCoin> CustomerCoins { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DecoreOption> DecoreOptions { get; set; }
        public virtual DbSet<Dish> Dishes { get; set; }
        public virtual DbSet<DishRecipe> DishRecipes { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Jukebox> Jukeboxes { get; set; }
        public virtual DbSet<MenuCategory> MenuCategories { get; set; }
        public virtual DbSet<Music> Musics { get; set; }
        public virtual DbSet<MusicGenre> MusicGenres { get; set; }
        public virtual DbSet<OrderChefAssignment> OrderChefAssignments { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<StockConsumption> StockConsumptions { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WaiterAssignment> WaiterAssignments { get; set; }
        public virtual DbSet<Waiter> Waiters { get; set; }
    }
}
