//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooknowAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Music()
        {
            this.Jukeboxes = new HashSet<Jukebox>();
        }
    
        public int MusicId { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public Nullable<int> GenreId { get; set; }
        public Nullable<int> DurationInSeconds { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jukebox> Jukeboxes { get; set; }
        public virtual MusicGenre MusicGenre { get; set; }
    }
}
