//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooknowAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> Stars { get; set; }
        public Nullable<int> RestaurantId { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual User User { get; set; }
    }
}
