//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooknowAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockConsumption
    {
        public int ConsumptionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> IngredientId { get; set; }
        public Nullable<decimal> QuantityUsed { get; set; }
        public Nullable<System.DateTime> UsedAt { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> restaurant_id { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Order Order { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
    }
}
